import { StyleSheet } from 'react-native';

export const authColors = {
  screen: '#EEF2FF',
  hero: '#1E3A8A',
  heroDeep: '#152C67',
  card: '#FFFFFF',
  cardBorder: '#DCE5F5',
  text: '#172033',
  textMuted: '#667085',
  textSoft: '#8A94A6',
  inputBg: '#F8FAFC',
  inputBorder: '#D6DFEE',
  inputBorderMuted: '#E4EAF5',
  inputBgMuted: '#FBFCFE',
  primary: '#1E3A8A',
  primaryPressed: '#17306F',
  primarySoft: '#E9F0FF',
  link: '#2146A8',
  divider: '#D8E1EF',
  socialBg: '#FFFFFF',
};

export const authShadows = {
  card: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 10,
  },
  field: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  button: {
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 7,
  },
};

export const authStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: authColors.hero,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  hero: {
    minHeight: 136,
    paddingTop: 0,
    paddingHorizontal: 20,
    paddingBottom: 0,
    backgroundColor: 'transparent',
  },
  backgroundWashTop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: authColors.hero,
  },
  backgroundWashBottom: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: authColors.hero,
  },
  backgroundPanelLeft: {
    position: 'absolute',
    top: 310,
    left: -90,
    width: 220,
    height: 520,
    borderRadius: 120,
    backgroundColor: 'rgba(255,255,255,0.16)',
    transform: [{ rotate: '16deg' }],
  },
  backgroundPanelRight: {
    position: 'absolute',
    bottom: -80,
    right: -70,
    width: 260,
    height: 340,
    borderRadius: 130,
    backgroundColor: 'rgba(255,255,255,0.06)',
    transform: [{ rotate: '-18deg' }],
  },
  heroOrbLarge: {
    position: 'absolute',
    top: 18,
    left: -38,
    width: 148,
    height: 148,
    borderRadius: 74,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroOrbSmall: {
    position: 'absolute',
    right: -26,
    top: 142,
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  heroPill: {
    position: 'absolute',
    right: 24,
    top: 34,
    width: 114,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    transform: [{ rotate: '18deg' }],
  },
  heroBand: {
    position: 'absolute',
    bottom: 272,
    right: 34,
    width: 132,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,0.08)',
    transform: [{ rotate: '-18deg' }],
  },
  heroDotCluster: {
    position: 'absolute',
    bottom: 168,
    left: 38,
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  card: {
    marginTop: -18,
    marginHorizontal: 16,
    borderRadius: 30,
    backgroundColor: authColors.card,
    borderWidth: 1,
    borderColor: authColors.cardBorder,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 20,
    ...authShadows.card,
  },
  cardHeader: {
    alignItems: 'center',
    marginBottom: 22,
  },
  iconBadge: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: authColors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D7E5FF',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    color: authColors.text,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  cardSubtitle: {
    marginTop: 6,
    fontSize: 16,
    lineHeight: 22,
    color: '#55657D',
    textAlign: 'center',
    fontWeight: '600',
  },
  helperText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 19,
    color: '#6C7A92',
    textAlign: 'center',
  },
  formSection: {
    marginBottom: 20,
  },
  sectionEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: '#73829B',
    marginBottom: 12,
  },
  subCard: {
    borderRadius: 22,
    backgroundColor: '#F9FBFF',
    borderWidth: 1,
    borderColor: '#E2EAF7',
    padding: 14,
  },
  optionalCard: {
    borderRadius: 22,
    backgroundColor: '#FCFDFF',
    borderWidth: 1,
    borderColor: '#E8EEF8',
    padding: 14,
  },
  fieldBlock: {
    marginBottom: 14,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: authColors.text,
  },
  optionalChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#F1F5FB',
  },
  optionalChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: authColors.textSoft,
  },
  fieldShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: authColors.inputBorder,
    backgroundColor: authColors.inputBg,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    ...authShadows.field,
  },
  fieldShellMuted: {
    borderColor: authColors.inputBorderMuted,
    backgroundColor: authColors.inputBgMuted,
  },
  fieldIcon: {
    marginRight: 12,
  },
  fieldInput: {
    flex: 1,
    fontSize: 16,
    lineHeight: 21,
    color: authColors.text,
    fontWeight: '500',
  },
  fieldTextValue: {
    flex: 1,
    fontSize: 16,
    lineHeight: 21,
    color: authColors.text,
    fontWeight: '500',
  },
  fieldPlaceholder: {
    color: authColors.textSoft,
  },
  trailingIconButton: {
    paddingLeft: 12,
    paddingVertical: 6,
  },
  textLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textLink: {
    fontSize: 14,
    fontWeight: '700',
    color: authColors.link,
  },
  rightLinkWrap: {
    alignItems: 'flex-end',
    marginTop: 2,
    marginBottom: 4,
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: authColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    ...authShadows.button,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 22,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: authColors.divider,
  },
  dividerPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: authColors.divider,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 12,
  },
  dividerText: {
    fontSize: 12,
    fontWeight: '700',
    color: authColors.textSoft,
  },
  socialButton: {
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DCE4F1',
    backgroundColor: authColors.socialBg,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  socialIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#F6F9FF',
  },
  socialButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#334155',
  },
  footerText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: '#5E6C84',
  },
  footerTextStrong: {
    color: authColors.link,
    fontWeight: '800',
  },
  inlineInfoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F7FAFF',
    borderWidth: 1,
    borderColor: '#E2EAF7',
    borderRadius: 18,
    padding: 14,
    marginBottom: 18,
  },
  inlineInfoTextWrap: {
    flex: 1,
    marginLeft: 10,
  },
  inlineInfoTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: authColors.text,
  },
  inlineInfoBody: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
    color: authColors.textMuted,
  },
  secondaryAction: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D6E1F2',
    backgroundColor: '#F5F8FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    ...authShadows.field,
  },
  secondaryActionIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E8F0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionText: {
    fontSize: 14,
    fontWeight: '700',
    color: authColors.link,
  },
});
